const productsList = [
  {
    name: 'Nombre producto',
    SKU: '56789',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    hasDiscount: 0.05,
    id: 1,
  },
  {
    name: 'Nombre producto',
    SKU: '46789',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    hasDiscount: 0.1,
    id: 2,
  },
  {
    name: 'Nombre producto',
    SKU: '36789',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    hasDiscount: 0,
    id: 3,
  },
  {
    name: 'Nombre producto',
    SKU: '26789',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    hasDiscount: 0,
    id: 4,
  },
  {
    name: 'Nombre producto',
    SKU: '16789',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    hasDiscount: 0,
    id: 5,
  },
  {
    name: 'Nombre producto',
    SKU: '06789',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    hasDiscount: 0,
    id: 6,
  },
  {
    name: 'Nombre producto',
    SKU: '56788',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    hasDiscount: 0,
    id: 7,
  },
  {
    name: 'Nombre producto',
    SKU: '56787',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    hasDiscount: 0,
    id: 8,
  },
  {
    name: 'Nombre producto',
    SKU: '56786',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    hasDiscount: 0,
    id: 9,
  },
  {
    name: 'Nombre producto',
    SKU: '56785',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    hasDiscount: 0,
    id: 10,
  },
  {
    name: 'Nombre producto',
    SKU: '56784',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    hasDiscount: 0,
    id: 11,
  },
  {
    name: 'Nombre producto',
    SKU: '56783',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    hasDiscount: 0,
    id: 12,
  },
];

const categoriesList = [
  {name: 'Todo', id: 1},
  {name: 'Finger Food', id: 2},
  {name: 'Dips', id: 3},
  {name: 'Hummus', id: 4},
  {name: 'Pastas', id: 5},
  {name: 'Botanas', id: 6},
  {name: 'Paninis', id: 7},
  {name: 'Ensaladas Verdes', id: 8},
  {name: 'Quinoas', id: 9},
  {name: 'Ensaladas', id: 10},
  {name: 'Paninis', id: 11},
  {name: 'Gelatinas de Yogourt', id: 12},
];

const clientMock = {
  firstName: 'John',
  lastName: 'Appleseed',
  cellphone: '1234564167',
  id: 'ds23456rfg4',
  debt: 50.45,
};

const couponMock = {
  code: '124dsf124',
  value: 50,
};

export {productsList, categoriesList, clientMock, couponMock};
