const productsList = [
  {
    name: 'Nombre producto',
    description: 'SKU:56789',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    id: 1,
  },
  {
    name: 'Nombre producto',
    description: 'SKU:56789',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    id: 2,
  },
  {
    name: 'Nombre producto',
    description: 'SKU:56789',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    id: 3,
  },
  {
    name: 'Nombre producto',
    description: 'SKU:56789',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    id: 4,
  },
  {
    name: 'Nombre producto',
    description: 'SKU:56789',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    id: 5,
  },
  {
    name: 'Nombre producto',
    description: 'SKU:56789',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    id: 6,
  },
  {
    name: 'Nombre producto',
    description: 'SKU:56789',
    image: 'https://picsum.photos/200',
    price: 145.55,
    unit: 'piece',
    inventory: 45,
    id: 7,
  },
];

const categories = [
  'Zapatos',
  'Bufandas',
  'Piel',
  'Gamusa',
  'Pantalones',
  'Mezclilla',
];

export {productsList, categories};
